### ISSUE TITLE
Invalid Session!

### ISSUE THREAD

**Issue by mrximple** [kom3/LineTimeline#3]
Sudah hampir seminggu saya menggunakan ini dan berjalan dengan lancar.
Tetapi mulai dari 2 hari lalu, cookies yang ada di tc sudah tidak bisa digunakan lagi...
Awalnya saya berfikir karena cookies/token telah expired, dan ketika saya login ulang dan memperbarui cookies/tokennya, ternyata tetap saya tidak bisa. Ketika di eksekusi selalu muncul invalid session! Padahal cookies nya sudah benar dan malah sudah saya perbarui.

Apakah pihak LINE Messenger telah memperbarui sistem mereka?
Berarti source code ini sudah tidak bisa lagi digunakan?

**Comment by YogaSakti** [comment]
Ya, bisa di bilang dari pihak line sudah memperbarui sistem mereka, karna sc saya sendiri pun mati juga. 
ada beberapa perubahan untuk sistem yang baru sih. tapi kemungkinan masih bisa di gunakan walau harus banyak perubahan
